language: cpp

sudo: required
dist: trusty

before_install:
    - pwd
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get update --fix-missing
    - sudo apt-get install -qq
        clang
        libfreetype6-dev
        libx11-dev
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libjack-dev
    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq
    - git clone --depth=1 --branch=master https://github.com/julianstorer/juce.git

compiler:
    - clang

branches:
    only:
        - master

script:
    - cd Builds/LinuxMakefile
    - make