language: cpp

before_install:
    - pwd
    - sudo apt-get install -qq
        clang
        libfreetype6-dev
        libx11-dev
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libjack-dev
    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq
    - sudo apt-get upgrade -qq
    - git clone --depth=1 --branch=master https://github.com/julianstorer/juce.git

compiler:
    - clang

env:
    global:
        - QUIET_ALREADY_VAR=1

branches:
    only:
        - master

script:
    - set -x
    - export DEBIAN_FRONTEND=noninteractive
    - cd Builds/LinuxMakefile && make