language: cpp

before_install:
    - pwd
    - git clone --depth=1 --branch=master https://github.com/julianstorer/juce.git
    - sudo apt-get update -qq
    - sudo apt-get install -qq
        clang
        g++
        gcc
        libfreetype6-dev
        libx11-dev
        libxinerama-dev
        libxrandr-dev
        libxcursor-dev
        libxcomposite-dev
        mesa-common-dev
        libasound2-dev
        freeglut3-dev
        libcurl4-gnutls-dev+
        libasound2-dev
        libjack-dev
    - sudo apt-get update -qq
    - sudo apt-get dist-upgrade

compiler:
    - clang
    - gcc

env:
    global:
        - QUIET_ALREADY_VAR=1

branches:
    only:
        - master

script: cd Builds/LinuxMakefile && make